spring:
  kafka:
    bootstrap-servers: localhost:9093
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: levani
    password: Aa12345.
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    web-application-type: servlet
server:
  port: 8003
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8002/eureka
  instance:
    hostname: localhost
