spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: levani
    password: Aa12345.
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    web-application-type: servlet
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: user_service_client_id
            client-secret: yp1ZmQE3EOBntaO83qaQ5QBUhmYRL9Ii
            authorization-grant-type: password
            scope: openid, profile, email
            authorization_endpoint: http://localhost:7777/realms/users/protocol/openid-connect/auth
            token_endpoint: http://localhost:7777/realms/users/protocol/openid-connect/token
            issuer_endpoint: http://localhost:7777/realms/users
        provider:
          keycloak:
            issuer-uri: http://localhost:7777/realms/users
    

server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8002/eureka
  instance:
    hostname: localhost
